server:
  port: 8080
spring:
  application:
    name: device-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/device_center
    username: root
    password: root