server:
  port: 8080
spring:
  application:
    name: device-center
  datasource:
    url: jdbc:mysql://192.168.1.4:3306/device_center
    username: root
    password: root
  redis:
    redisson:
      file: classpath:redisson.yml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
